name: Deploy to AWS

on:
  push:
    branches:
      - main # O deploy será feito sempre que atualizar a branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executando deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/evento360
            git fetch --all
            git reset --hard origin/main

            # Atualiza o email oficial do Resend na nuvem automaticamente
            sed -i 's/^RESEND_FROM_EMAIL=.*/RESEND_FROM_EMAIL="Evento360 <nao-responda@evento360.lat>"/' .env || true
            sed -i 's/^RESEND_FROM_EMAIL=.*/RESEND_FROM_EMAIL="Evento360 <nao-responda@evento360.lat>"/' backend/.env || true

            sudo docker compose --profile app up -d --build
